version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: slave
  ignore:
  - dependency-name: com.github.1951FDG.AndroidPerformanceMonitor:blockcanary-android
    versions:
    - ">= 1.6.a"
    - "< 1.7"
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - "> 1.3.72"
  - dependency-name: tools.fastlane:screengrab
    versions:
    - ">= 2.0.a"
    - "< 2.1"
