---
exclude_paths:
  - '**.json'
  - '**.lock'
  - '**.xml'
  - '**.yml'
  - 'libraries/sqlite-ndk/src/main/java/com/almworks/**'
  - 'libraries/sqlite-ndk/src/main/java/io/requery/**'
  - 'libraries/sqlite-ndk/src/main/java/org/javolution/**'
  - 'libraries/sqlite-ndk/src/main/java/org/sqlite/**'
  - 'libraries/sqlite-ndk/src/main/jni/**'
  - 'fastlane/**'
